"""
Artifact download/listing API — Phase 7 implementation (M5/M6).

Artifacts themselves are generated by the agent loop (POST /api/agent) via
the generate_docx/xlsx/pdf/csv/json tools; these endpoints let the UI list
a task's artifacts and download the underlying file, and let a client
independently verify a downloaded file's integrity against the recorded hash.
"""
import logging
import os

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from database.session import get_db
from database.models import Artifact
from artifacts.storage import resolve_artifact_path, sha256_file

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/artifacts")
def list_artifacts(task_id: str | None = None, db: Session = Depends(get_db)):
    """List artifacts, optionally filtered by task_id."""
    query = db.query(Artifact)
    if task_id:
        query = query.filter(Artifact.task_id == task_id)
    artifacts = query.order_by(Artifact.created_at.desc()).all()
    return [
        {
            "id": a.id,
            "task_id": a.task_id,
            "filename": a.filename,
            "content_type": a.content_type,
            "file_hash": a.file_hash,
            "created_at": a.created_at,
        }
        for a in artifacts
    ]


@router.get("/artifacts/{artifact_id}/download")
def download_artifact(artifact_id: str, db: Session = Depends(get_db)):
    """Stream the artifact's underlying file, verifying it's still intact
    (hash unchanged since generation) before serving it."""
    artifact = db.query(Artifact).filter(Artifact.id == artifact_id).first()
    if not artifact:
        raise HTTPException(status_code=404, detail="Artifact not found")

    path = resolve_artifact_path(artifact.task_id, artifact.id, artifact.filename)
    if not os.path.isfile(path):
        raise HTTPException(status_code=410, detail="Artifact file is missing from storage")

    if artifact.file_hash:
        current_hash = sha256_file(path)
        if current_hash != artifact.file_hash:
            logger.error("Artifact %s hash mismatch: expected %s, got %s", artifact_id, artifact.file_hash, current_hash)
            raise HTTPException(status_code=409, detail="Artifact file integrity check failed")

    return FileResponse(path, filename=artifact.filename, media_type=artifact.content_type or "application/octet-stream")


@router.get("/artifacts/{artifact_id}/verify")
def verify_artifact(artifact_id: str, db: Session = Depends(get_db)):
    """Recompute the artifact's file hash and confirm it matches the recorded value."""
    artifact = db.query(Artifact).filter(Artifact.id == artifact_id).first()
    if not artifact:
        raise HTTPException(status_code=404, detail="Artifact not found")

    path = resolve_artifact_path(artifact.task_id, artifact.id, artifact.filename)
    if not os.path.isfile(path):
        return {"id": artifact_id, "status": "missing", "verified": False}

    current_hash = sha256_file(path)
    return {
        "id": artifact_id,
        "status": "ok",
        "verified": current_hash == artifact.file_hash,
        "recorded_hash": artifact.file_hash,
        "current_hash": current_hash,
    }
